#!/usr/bin/env bash
# Configure Nginx to add X-Served-By HTTP header showing the hostname of the server

# Update and install Nginx
apt-get update -y
apt-get install -y nginx

# Get the server hostname
hostname=$(hostname)

# Configure default Nginx server to add custom HTTP header
cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
        add_header X-Served-By \$hostname;
    }
}
EOF

# Test Nginx configuration
nginx -t

# Restart Nginx
systemctl restart nginx
