#!/usr/bin/env bash
#Bash script that installs HAProxy & makes configurations

apt-get -y install software-properties-common
add-apt-repository ppa:vbernat/haproxy-1.8
apt-get update
apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
printf %s "listen 5819-webs
    bind *:80
    mode http
    balance roundrobin
    server web-01 18.208.149.224:80 check
    server web-02 98.93.251.113:80 check
" >> /etc/haproxy/haproxy.cfg
service haproxy restart
