#!/usr/bin/env bash
#This script installs Nginx, configures it to serve a page containing 'Holberton School', and ensures it runs on port 80

#update package lists
apt-get update -y

#Install Nginx
apt-get install -y nginx

#Ensure Nginx is started
service nginx start

#Create a custom index.html with required content
echo "Holberton School for the win" > /var/www/html/index.html

#Ensure Nginx is running after file update
service nginx restart
