#!/usr/bin/env bash
# Configures Nginx to redirect /redirect_me to another URL with 301 status

# Install nginx if not already installed
sudo apt-get update -y
sudo apt-get install -y nginx

# Create the redirection
sudo bash -c 'cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF'

# Restart nginx to apply changes
sudo systemctl restart nginx
